**Import Required Libraries**

In [ ]:
! pip install pandas numpy

import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**Load Dataset 1 & 2**

In [ ]:
loan_data_1 = pd.read_csv('/content/Loan_Approval_Data_Set_1.csv')
loan_data_2 = pd.read_csv('/content/Loan_Approval_Data_Set_2.csv')

**Display Head**

In [ ]:
print("Dataset 1 Preview")
print(loan_data_1.head())

print("\nDataset 2 Preview")
print(loan_data_2.head())

Dataset 1 Preview
     ID ApplicationDate  AnnualIncome EmploymentStatus  Experience  \
0  A001      01-01-2018         39948         Employed          22
1  A002      02-01-2018         39709         Employed          15
2  A003      03-01-2018         40724         Employed          26
3  A004      04-01-2018         69084         Employed          34
4  A005      05-01-2018        103264         Employed          17

   LoanDuration  NumberOfDependents  MonthlyDebtPayments  \
0            48                   2                  183
1            48                   1                  496
2            36                   2                  902
3            96                   1                  755
4            36                   1                  274

   NumberOfOpenCreditLines  BankruptcyHistory  PreviousLoanDefaults  \
0                        1                  0                     0
1                        5                  0                     0
2                        2                  0                     0
3                        2                  0                     0
4                        0                  0                     0

   LengthOfCreditHistory  CheckingAccountBalance  TotalLiabilities  NetWorth  \
0                      9                    1202             19183    126928
1                      9                    3460              9595     43609
2                     22                     895            128874      5205
3                     10                    1217              5370     99452
4                     27                    4981             17286    227019

   LoanApproved
0             0
1             0
2             0
3             0
4             1

Dataset 2 Preview
  ApplicationDate  Age  CreditScore EducationLevel  Experience  LoanAmount  \
0      01-01-2018   45          617         Master        22.0       13152
1      02-01-2018   38          628      Associate         NaN       26045
2      03-01-2018   47          570       Bachelor        26.0       17627
3      04-01-2018   58          545    High School        34.0       37898
4      05-01-2018   37          594      Associate        17.0        9184

  MaritalStatus HomeOwnershipStatus    ID  CreditCardUtilizationRate  \
0       Married                 Own  A001                      35.40
1        Single            Mortgage  A002                       8.78
2       Married                Rent  A003                      13.70
3        Single            Mortgage  A004                       2.67
4       Married            Mortgage  A005                       3.20

   NumberOfCreditInquiries         LoanPurpose  PaymentHistory  \
0                        2                Home              29
1                        3  Debt Consolidation              21
2                        0           Education              20
3                        1                Home              27
4                        0  Debt Consolidation              26

   SavingsAccountBalance  TotalAssets  JobTenure  InterestRate RiskScore
0                   7632       146111         11         22.75        49
1                   4627        53204          3         20.10        XX
2                    886        25176          6         21.25        XX
3                   1675       104822          5         30.09        54
4                   1555       244305          5         17.59        36

**Convert Risk Score to numeric**

In [ ]:
loan_data_2['RiskScore'] = (
    loan_data_2['RiskScore']
    .replace('XX', np.nan)
)

loan_data_2['RiskScore'] = pd.to_numeric(
    loan_data_2['RiskScore'],
    errors='coerce'
)

**Check unique IDs**

In [ ]:
print("Unique IDs in Dataset 1:",
      loan_data_1['ID'].nunique())

print("Unique IDs in Dataset 2:",
      loan_data_2['ID'].nunique())

Unique IDs in Dataset 1: 20000
Unique IDs in Dataset 2: 20000

**Merge datasets**

In [ ]:
loan_dataset = pd.merge(
    loan_data_1,
    loan_data_2,
    on='ID',
    how='inner',
    suffixes=('_financial', '_demographic')
)

**Dimensions after merge**

In [ ]:
print("Merged Dataset Shape:")
print(loan_dataset.shape)

Merged Dataset Shape:
(20000, 33)

**Duplicate check**

In [ ]:
print("Duplicate Records:",
      loan_dataset.duplicated().sum())

Duplicate Records: 0

**Missing values**

In [ ]:
print("Missing Values:")
print(loan_dataset.isnull().sum())

Missing Values:
ID                                0
ApplicationDate_financial         0
AnnualIncome                      0
EmploymentStatus                  0
Experience_financial              0
LoanDuration                      0
NumberOfDependents                0
MonthlyDebtPayments               0
NumberOfOpenCreditLines           0
BankruptcyHistory                 0
PreviousLoanDefaults              0
LengthOfCreditHistory             0
CheckingAccountBalance            0
TotalLiabilities                  0
NetWorth                          0
LoanApproved                      0
ApplicationDate_demographic       0
Age                               0
CreditScore                       0
EducationLevel                    0
Experience_demographic          666
LoanAmount                        0
MaritalStatus                    15
HomeOwnershipStatus               0
CreditCardUtilizationRate         0
NumberOfCreditInquiries           0
LoanPurpose                       0
PaymentHistory                    0
SavingsAccountBalance             0
TotalAssets                       0
JobTenure                         0
InterestRate                      0
RiskScore                      1275
dtype: int64

**Preview merged dataset**

In [ ]:
loan_dataset.head()

,ID,ApplicationDate_financial,AnnualIncome,EmploymentStatus,Experience_financial,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,...,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,A001,01-01-2018,39948,Employed,22,48,2,183,1,0,...,Own,35.40,2,Home,29,7632,146111,11,22.75,49.0
1,A002,02-01-2018,39709,Employed,15,48,1,496,5,0,...,Mortgage,8.78,3,Debt Consolidation,21,4627,53204,3,20.10,NaN
2,A003,03-01-2018,40724,Employed,26,36,2,902,2,0,...,Rent,13.70,0,Education,20,886,25176,6,21.25,NaN
3,A004,04-01-2018,69084,Employed,34,96,1,755,2,0,...,Mortgage,2.67,1,Home,27,1675,104822,5,30.09,54.0
4,A005,05-01-2018,103264,Employed,17,36,1,274,0,0,...,Mortgage,3.20,0,Debt Consolidation,26,1555,244305,5,17.59,36.0

Warning: Total number of columns (33) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
valid_rows = loan_dataset['Experience_demographic'].notna()

matches = (
    loan_dataset.loc[valid_rows, 'Experience_financial']
    ==
    loan_dataset.loc[valid_rows, 'Experience_demographic']
).sum()

total = valid_rows.sum()

print("Matches:", matches)
print("Total Compared:", total)
print("Match Percentage:", round(matches/total*100, 2), "%")

Matches: 19334
Total Compared: 19334
Match Percentage: 100.0 %

In [ ]:
# Drop duplicate experience column
loan_dataset.drop(
    columns=['Experience_demographic'],
    inplace=True
)

# Rename remaining column
loan_dataset.rename(
    columns={'Experience_financial': 'Experience'},
    inplace=True
)

In [ ]:
loan_dataset.head()

,ID,ApplicationDate_financial,AnnualIncome,EmploymentStatus,Experience,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,...,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,A001,2018-01-01,39948,Employed,22,48,2,183,1,0,...,Own,35.40,2,Home,29,7632,146111,11,22.75,49.0
1,A002,2018-01-02,39709,Employed,15,48,1,496,5,0,...,Mortgage,8.78,3,Debt Consolidation,21,4627,53204,3,20.10,NaN
2,A003,2018-01-03,40724,Employed,26,36,2,902,2,0,...,Rent,13.70,0,Education,20,886,25176,6,21.25,NaN
3,A004,2018-01-04,69084,Employed,34,96,1,755,2,0,...,Mortgage,2.67,1,Home,27,1675,104822,5,30.09,54.0
4,A005,2018-01-05,103264,Employed,17,36,1,274,0,0,...,Mortgage,3.20,0,Debt Consolidation,26,1555,244305,5,17.59,36.0